/api/shapes:
  get:
    summary: Returns a list of shapes
    description: Retrieve a list of shapes. Can be used to populate a list of shapes when prototyping or testing an API.*
    responses:
      200:
        description: A JSON array of shapes
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The category ID.
                        example: 1
                      name:
                        type: string
                        description: The shape name.
                        example: Coupé
                      imgUrl:
                        type: string
                        description: The url to the shape svg
                        example: ./data/coupé.svg
                      createdAt:
                        type: Date
                        description: The created date of the shape
                        example: FILL IN
                      updatedAt:
                        type: Date
                        description: The updated date of the shape
                        example: FILL IN